Blog app - Views
Gh-Reza/BlogApp pull request #7
Opened 2023-11-02 16:59 UTC by Gh-Reza

## Changes:

- Created necessary variables for Post and User actions
- Added the basic view for: index and show actions of PostController and UserContrroller

2023-11-02 18:23 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle:

Hi @Gh-Reza, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
-  Implemented some project requirements. :heavy_check_mark: 
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct Gitflow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-02 18:23 UTC, Qoosim commented on app/views/users/index.html.erb
> +</ul>
- [ ] Great job creating views for your app. However, there're few things to do before you could move on to the next milestone.
- [ ] It is required that you index view page should match the [wireframe](https://raw.githubusercontent.com/microverseinc/curriculum-rails/main/blog-app/images/blog_root_users.png?token=GHSAT0AAAAAACJF5B2AX2L63CTAV4ZLMVOGZKD6ETQ). :point_down: 

![username](https://github.com/Gh-Reza/BlogApp/assets/26597432/ae037b3f-2d55-4ab1-961f-62fb4130bbb3)

- After creating two users and starting your app, this is how your view page displayed. :point_down: 

![your-page](https://github.com/Gh-Reza/BlogApp/assets/26597432/e46451ce-e996-40bf-a985-e90751a15d63)

2023-11-02 18:23 UTC, Qoosim commented on app/views/users/index.html.erb
> +    <li><h1><%= user.name %></h1></li>
- [ ] It is also required that clicking on each user take us to the user show page. Your user is not clickable. Kindly fix that.

### Expected show page

![show-page](https://github.com/Gh-Reza/BlogApp/assets/26597432/8ac130f9-912f-493d-bb50-f468e72cb7ae)

### Your Page
[your-app.webm](https://github.com/Gh-Reza/BlogApp/assets/26597432/7b248587-7add-40f6-b94f-659181835153)

2023-11-02 18:23 UTC, Qoosim commented on app/views/users/show.html.erb
> +</div>
- [ ] User show page is required to a button that has `See All Posts` text that opens  user's post index page. That is yet to be implemented. Kindly fix that. It should look something similar to this. :point_down: 

```
<button>
<%= link_to 'See all Post', user_posts_path(@user) %>
</button>
``` 

### Expected Page
![all-posts](https://github.com/Gh-Reza/BlogApp/assets/26597432/def87b13-9f0a-4ae1-973e-14ea0b6b82a5)

2023-11-03 11:15 UTC, shella12 approved these changes
Hi @Gh-Reza, 


## Status : APPROVED 🥳 🥳 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif"/>

## Highlights

- Added click events ✔️ 
- Views match wireframe 👍 
- Implemented all requirements 👏 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-03 11:20 UTC, merged